apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cart-domain
spec:
  generators:
    - list:
        elements:
          - cluster: dev
            url: 'https://kubernetes.default.svc'
          - cluster: sut
            url: 'https://kubernetes.default.svc'
  template:
    metadata:
      name: '{{cluster}}-app'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/AstronutDev/idp-app.git'
        targetRevision: HEAD
        path: '{{cluster}}/'
      destination:
        server: https://kubernetes.default.svc
        namespace: pg
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: true