apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cart-domain
spec:
  generators:
    - list:
        elements:
          - cluster: dev
            url: 'https://kubernetes.default.svc'
          - cluster: sut
            url: 'https://kubernetes.default.svc'
  template:
    metadata:
      name: '{{cluster}}-app'
    spec:
      project: team-b
      source:
        repoURL: 'https://github.com/AstronutDev/nonprod-k8s-manifest.git'
        targetRevision: HEAD
        path: '{{cluster}}/pedjeab/payment'
      destination:
        server: https://kubernetes.default.svc
        namespace: pg
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: true