# apiVersion: argoproj.io/v1alpha1
# kind: ApplicationSet
# metadata:
#   name: idp-app
# spec:
#   generators:
#     - list:
#         elements:
#           - cluster: dev
#             url: 'https://kubernetes.default.svc'
#           - cluster: sut
#             url: 'https://kubernetes.default.svc'
#   template:
#     metadata:
#       name: '{{cluster}}-app'
#     spec:
#       project: default
#       source:
#         repoURL: 'https://github.com/AstronutDev/idp-app.git'
#         targetRevision: HEAD
#         path: 'platform'
#       destination:
#         server: https://kubernetes.default.svc
#         namespace: argocd
#       syncPolicy:
#         automated:
#           prune: true
#           selfHeal: true
#           allowEmpty: true

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: idp-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/AstronutDev/idp-app.git'
    targetRevision: HEAD
    path: 'platform'
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true