apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cart
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:AstronutDev/idp-app.git
    targetRevision: HEAD
    path: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: pg
  syncPolicy:
    automated:
      prune: true
      selfHeal: true