apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  policy.csv: |
    g, nutx, proj:default:read-write
    p, proj:default:read-write, applications, get, *, allow

    g, nongkai, proj:team-a:read-write
    g, nongkai, proj:operator:read-only

    g, nongped, proj:team-b:read-write
    g, nongped, proj:team-a:read-only

    p, pukjee, applications, *, */*, allow
    p, pukjee, projects, *, */*, allow


  # nongkai teamA, kai123456
  # nongped teamB, ped123456
  # pukjee infra, jee123456