apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: team-a
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
spec:

  description: Team A
  destinations:
  - name: 'teamA'
    namespace: 'pg'
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: ""
    kind: Namespace


  roles:
  - description: Read Only
    name: read-only
    policies:
    - p, proj:team-a:read-only, applications, get, team-a/*, allow
  - description: Read Write
    name: read-write   
    policies:
    - p, proj:team-a:read-write, applications, get, team-a/*, allow
    - p, proj:team-a:read-write, applications, sync, team-a/*, allow
    - p, proj:team-a:read-write, applications, update, team-a/*, allow    
    - p, proj:team-a:read-write, applications, delete, team-a/*, deny
  sourceRepos:
  - https://github.com/kostis-codefresh/intro-argocd-rbac.git
  - https://github.com/AstronutDev/nonprod-k8s-manifest.git
  - https://github.com/AstronutDev/nonprod-k8s-config.git
  
